/* ScanDixit interface translations v1.0.0 */
(function(root){
'use strict';
const STORE='ficard.language.v2';
const maps={
en:{
'SCANSIONA E SCOPRI':'SCAN AND DISCOVER','ScanDixit · informazioni prodotto':'ScanDixit · product information','Hai un dubbio':'Questions about','su un prodotto?':'a product?','Inquadralo. ScanDixit prepara la scheda e ti porta alle recensioni di chi l’ha già acquistato.':'Scan it. ScanDixit prepares the product sheet and takes you to reviews from people who already bought it.','Metodo di riconoscimento':'Recognition method','▦  Codice a barre':'▦  Barcode','▤  Etichetta / OCR':'▤  Label / OCR','Scansiona il prodotto':'Scan the product','Tieni tutto il codice nell’inquadratura e muovi il telefono lentamente; evita riflessi sulla confezione.':'Keep the whole code in frame and move the phone slowly; avoid reflections on the package.','Apri la fotocamera':'Open camera','Chiudi fotocamera':'Close camera','Accendi / spegni torcia':'Turn flashlight on / off','＋ Scegli o scatta una foto del codice':'＋ Choose or take a photo of the code','oppure inserisci il codice':'or enter the code','Cerca codice':'Search code','Leggi l’etichetta':'Read the label','Fotografa la targhetta o il retro della confezione: l’OCR legge marca e modello per restringere la ricerca.':'Photograph the label or back of the package: OCR reads brand and model to narrow the search.','＋   Scatta o scegli una foto':'＋   Take or choose a photo','Controlla il testo riconosciuto prima di cercare.':'Check the recognized text before searching.','Il testo riconosciuto comparirà qui; puoi correggere marca o modello.':'Recognized text will appear here; you can correct the brand or model.','Cerca marca e modello':'Search brand and model','Lettura delle barre con recupero automatico delle cifre tramite OCR.':'Reading bars with automatic digit recovery via OCR.','Annulla analisi':'Cancel analysis','Il codice identifica la confezione; la scheda riporta soltanto i dati presenti nei cataloghi collegati. I dati mancanti restano esplicitamente tali.':'The code identifies the package; the sheet only reports data available in connected catalogs. Missing data remains explicitly marked as unavailable.','Codice acquisito':'Code acquired','Scheda prodotto':'Product sheet','Cerco il prodotto…':'Searching for product…','Caratteristiche principali':'Main features','Informazioni aggiuntive':'Additional information','Leggi opinioni del prodotto':'Read product reviews','Il prodotto fisico resta al centro. ScanDixit aggiunge le informazioni che aiutano a scegliere.':'The physical product stays at the center. ScanDixit adds information that helps you choose.','Torna a FiCard':'Back to Fi-Card'},
fr:{
'SCANSIONA E SCOPRI':'SCANNEZ ET DÉCOUVREZ','ScanDixit · informazioni prodotto':'ScanDixit · informations produit','Hai un dubbio':'Un doute sur','su un prodotto?':'un produit ?','Inquadralo. ScanDixit prepara la scheda e ti porta alle recensioni di chi l’ha già acquistato.':'Scannez-le. ScanDixit prépare la fiche et vous mène aux avis de ceux qui l’ont déjà acheté.','Metodo di riconoscimento':'Méthode de reconnaissance','▦  Codice a barre':'▦  Code-barres','▤  Etichetta / OCR':'▤  Étiquette / OCR','Scansiona il prodotto':'Scannez le produit','Tieni tutto il codice nell’inquadratura e muovi il telefono lentamente; evita riflessi sulla confezione.':'Gardez tout le code dans le cadre et déplacez lentement le téléphone ; évitez les reflets sur l’emballage.','Apri la fotocamera':'Ouvrir l’appareil photo','Chiudi fotocamera':'Fermer l’appareil photo','Accendi / spegni torcia':'Allumer / éteindre la lampe','＋ Scegli o scatta una foto del codice':'＋ Choisir ou prendre une photo du code','oppure inserisci il codice':'ou saisissez le code','Cerca codice':'Rechercher le code','Leggi l’etichetta':'Lire l’étiquette','Fotografa la targhetta o il retro della confezione: l’OCR legge marca e modello per restringere la ricerca.':'Photographiez l’étiquette ou le dos de l’emballage : l’OCR lit la marque et le modèle pour affiner la recherche.','＋   Scatta o scegli una foto':'＋   Prendre ou choisir une photo','Controlla il testo riconosciuto prima di cercare.':'Vérifiez le texte reconnu avant de rechercher.','Il testo riconosciuto comparirà qui; puoi correggere marca o modello.':'Le texte reconnu apparaîtra ici ; vous pouvez corriger la marque ou le modèle.','Cerca marca e modello':'Rechercher marque et modèle','Lettura delle barre con recupero automatico delle cifre tramite OCR.':'Lecture des barres avec récupération automatique des chiffres par OCR.','Annulla analisi':'Annuler l’analyse','Il codice identifica la confezione; la scheda riporta soltanto i dati presenti nei cataloghi collegati. I dati mancanti restano esplicitamente tali.':'Le code identifie l’emballage ; la fiche affiche uniquement les données présentes dans les catalogues connectés. Les données manquantes restent indiquées comme telles.','Codice acquisito':'Code acquis','Scheda prodotto':'Fiche produit','Cerco il prodotto…':'Recherche du produit…','Caratteristiche principali':'Caractéristiques principales','Informazioni aggiuntive':'Informations supplémentaires','Leggi opinioni del prodotto':'Lire les avis sur le produit','Il prodotto fisico resta al centro. ScanDixit aggiunge le informazioni che aiutano a scegliere.':'Le produit physique reste au centre. ScanDixit ajoute les informations qui aident à choisir.','Torna a FiCard':'Retour à Fi-Card'},
es:{
'SCANSIONA E SCOPRI':'ESCANEA Y DESCUBRE','ScanDixit · informazioni prodotto':'ScanDixit · información del producto','Hai un dubbio':'¿Tienes dudas','su un prodotto?':'sobre un producto?','Inquadralo. ScanDixit prepara la scheda e ti porta alle recensioni di chi l’ha già acquistato.':'Escanéalo. ScanDixit prepara la ficha y te lleva a las reseñas de quienes ya lo han comprado.','Metodo di riconoscimento':'Método de reconocimiento','▦  Codice a barre':'▦  Código de barras','▤  Etichetta / OCR':'▤  Etiqueta / OCR','Scansiona il prodotto':'Escanea el producto','Tieni tutto il codice nell’inquadratura e muovi il telefono lentamente; evita riflessi sulla confezione.':'Mantén todo el código dentro del encuadre y mueve el teléfono lentamente; evita reflejos en el envase.','Apri la fotocamera':'Abrir cámara','Chiudi fotocamera':'Cerrar cámara','Accendi / spegni torcia':'Encender / apagar linterna','＋ Scegli o scatta una foto del codice':'＋ Elige o toma una foto del código','oppure inserisci il codice':'o introduce el código','Cerca codice':'Buscar código','Leggi l’etichetta':'Leer la etiqueta','Fotografa la targhetta o il retro della confezione: l’OCR legge marca e modello per restringere la ricerca.':'Fotografía la etiqueta o la parte trasera del envase: el OCR lee marca y modelo para afinar la búsqueda.','＋   Scatta o scegli una foto':'＋   Toma o elige una foto','Controlla il testo riconosciuto prima di cercare.':'Comprueba el texto reconocido antes de buscar.','Il testo riconosciuto comparirà qui; puoi correggere marca o modello.':'El texto reconocido aparecerá aquí; puedes corregir la marca o el modelo.','Cerca marca e modello':'Buscar marca y modelo','Lettura delle barre con recupero automatico delle cifre tramite OCR.':'Lectura de barras con recuperación automática de dígitos mediante OCR.','Annulla analisi':'Cancelar análisis','Il codice identifica la confezione; la scheda riporta soltanto i dati presenti nei cataloghi collegati. I dati mancanti restano esplicitamente tali.':'El código identifica el envase; la ficha solo muestra datos presentes en los catálogos conectados. Los datos que faltan se indican como tales.','Codice acquisito':'Código adquirido','Scheda prodotto':'Ficha del producto','Cerco il prodotto…':'Buscando producto…','Caratteristiche principali':'Características principales','Informazioni aggiuntive':'Información adicional','Leggi opinioni del prodotto':'Leer opiniones del producto','Il prodotto fisico resta al centro. ScanDixit aggiunge le informazioni che aiutano a scegliere.':'El producto físico sigue siendo el centro. ScanDixit añade información que ayuda a elegir.','Torna a FiCard':'Volver a Fi-Card'},
pt:{
'SCANSIONA E SCOPRI':'DIGITALIZE E DESCUBRA','ScanDixit · informazioni prodotto':'ScanDixit · informações do produto','Hai un dubbio':'Tem dúvidas','su un prodotto?':'sobre um produto?','Inquadralo. ScanDixit prepara la scheda e ti porta alle recensioni di chi l’ha già acquistato.':'Digitalize-o. O ScanDixit prepara a ficha e leva-o às avaliações de quem já o comprou.','Metodo di riconoscimento':'Método de reconhecimento','▦  Codice a barre':'▦  Código de barras','▤  Etichetta / OCR':'▤  Etiqueta / OCR','Scansiona il prodotto':'Digitalize o produto','Tieni tutto il codice nell’inquadratura e muovi il telefono lentamente; evita riflessi sulla confezione.':'Mantenha todo o código no enquadramento e mova o telefone lentamente; evite reflexos na embalagem.','Apri la fotocamera':'Abrir câmara','Chiudi fotocamera':'Fechar câmara','Accendi / spegni torcia':'Ligar / desligar lanterna','＋ Scegli o scatta una foto del codice':'＋ Escolher ou tirar uma foto do código','oppure inserisci il codice':'ou introduza o código','Cerca codice':'Pesquisar código','Leggi l’etichetta':'Ler a etiqueta','Fotografa la targhetta o il retro della confezione: l’OCR legge marca e modello per restringere la ricerca.':'Fotografe a etiqueta ou o verso da embalagem: o OCR lê a marca e o modelo para refinar a pesquisa.','＋   Scatta o scegli una foto':'＋   Tirar ou escolher uma foto','Controlla il testo riconosciuto prima di cercare.':'Verifique o texto reconhecido antes de pesquisar.','Il testo riconosciuto comparirà qui; puoi correggere marca o modello.':'O texto reconhecido aparecerá aqui; pode corrigir a marca ou o modelo.','Cerca marca e modello':'Pesquisar marca e modelo','Lettura delle barre con recupero automatico delle cifre tramite OCR.':'Leitura das barras com recuperação automática dos dígitos por OCR.','Annulla analisi':'Cancelar análise','Il codice identifica la confezione; la scheda riporta soltanto i dati presenti nei cataloghi collegati. I dati mancanti restano esplicitamente tali.':'O código identifica a embalagem; a ficha apresenta apenas dados disponíveis nos catálogos ligados. Os dados em falta permanecem indicados como tal.','Codice acquisito':'Código adquirido','Scheda prodotto':'Ficha do produto','Cerco il prodotto…':'A procurar produto…','Caratteristiche principali':'Características principais','Informazioni aggiuntive':'Informações adicionais','Leggi opinioni del prodotto':'Ler avaliações do produto','Il prodotto fisico resta al centro. ScanDixit aggiunge le informazioni che aiutano a scegliere.':'O produto físico continua no centro. O ScanDixit acrescenta informação que ajuda a escolher.','Torna a FiCard':'Voltar ao Fi-Card'},
nl:{
'SCANSIONA E SCOPRI':'SCAN EN ONTDEK','ScanDixit · informazioni prodotto':'ScanDixit · productinformatie','Hai un dubbio':'Twijfel je over','su un prodotto?':'een product?','Inquadralo. ScanDixit prepara la scheda e ti porta alle recensioni di chi l’ha già acquistato.':'Scan het. ScanDixit maakt de productfiche en brengt je naar reviews van mensen die het al hebben gekocht.','Metodo di riconoscimento':'Herkenningsmethode','▦  Codice a barre':'▦  Barcode','▤  Etichetta / OCR':'▤  Etiket / OCR','Scansiona il prodotto':'Scan het product','Tieni tutto il codice nell’inquadratura e muovi il telefono lentamente; evita riflessi sulla confezione.':'Houd de volledige code in beeld en beweeg de telefoon langzaam; vermijd reflecties op de verpakking.','Apri la fotocamera':'Camera openen','Chiudi fotocamera':'Camera sluiten','Accendi / spegni torcia':'Zaklamp aan / uit','＋ Scegli o scatta una foto del codice':'＋ Kies of maak een foto van de code','oppure inserisci il codice':'of voer de code in','Cerca codice':'Code zoeken','Leggi l’etichetta':'Lees het etiket','Fotografa la targhetta o il retro della confezione: l’OCR legge marca e modello per restringere la ricerca.':'Fotografeer het etiket of de achterkant van de verpakking: OCR leest merk en model om de zoekopdracht te verfijnen.','＋   Scatta o scegli una foto':'＋   Maak of kies een foto','Controlla il testo riconosciuto prima di cercare.':'Controleer de herkende tekst voordat je zoekt.','Il testo riconosciuto comparirà qui; puoi correggere marca o modello.':'De herkende tekst verschijnt hier; je kunt merk of model corrigeren.','Cerca marca e modello':'Merk en model zoeken','Lettura delle barre con recupero automatico delle cifre tramite OCR.':'Barcodes lezen met automatische cijferherkenning via OCR.','Annulla analisi':'Analyse annuleren','Il codice identifica la confezione; la scheda riporta soltanto i dati presenti nei cataloghi collegati. I dati mancanti restano esplicitamente tali.':'De code identificeert de verpakking; de fiche toont alleen gegevens uit gekoppelde catalogi. Ontbrekende gegevens blijven duidelijk als ontbrekend aangegeven.','Codice acquisito':'Code vastgelegd','Scheda prodotto':'Productfiche','Cerco il prodotto…':'Product zoeken…','Caratteristiche principali':'Belangrijkste kenmerken','Informazioni aggiuntive':'Aanvullende informatie','Leggi opinioni del prodotto':'Productreviews lezen','Il prodotto fisico resta al centro. ScanDixit aggiunge le informazioni che aiutano a scegliere.':'Het fysieke product blijft centraal staan. ScanDixit voegt informatie toe die helpt bij je keuze.','Torna a FiCard':'Terug naar Fi-Card'},
de:{
'SCANSIONA E SCOPRI':'SCANNEN UND ENTDECKEN','ScanDixit · informazioni prodotto':'ScanDixit · Produktinformationen','Hai un dubbio':'Fragen zu','su un prodotto?':'einem Produkt?','Inquadralo. ScanDixit prepara la scheda e ti porta alle recensioni di chi l’ha già acquistato.':'Scanne es. ScanDixit erstellt das Produktblatt und führt dich zu Bewertungen von Personen, die es bereits gekauft haben.','Metodo di riconoscimento':'Erkennungsmethode','▦  Codice a barre':'▦  Barcode','▤  Etichetta / OCR':'▤  Etikett / OCR','Scansiona il prodotto':'Produkt scannen','Tieni tutto il codice nell’inquadratura e muovi il telefono lentamente; evita riflessi sulla confezione.':'Halte den gesamten Code im Bild und bewege das Telefon langsam; vermeide Reflexionen auf der Verpackung.','Apri la fotocamera':'Kamera öffnen','Chiudi fotocamera':'Kamera schließen','Accendi / spegni torcia':'Taschenlampe ein / aus','＋ Scegli o scatta una foto del codice':'＋ Foto des Codes auswählen oder aufnehmen','oppure inserisci il codice':'oder Code eingeben','Cerca codice':'Code suchen','Leggi l’etichetta':'Etikett lesen','Fotografa la targhetta o il retro della confezione: l’OCR legge marca e modello per restringere la ricerca.':'Fotografiere das Etikett oder die Rückseite der Verpackung: OCR liest Marke und Modell, um die Suche einzugrenzen.','＋   Scatta o scegli una foto':'＋   Foto aufnehmen oder auswählen','Controlla il testo riconosciuto prima di cercare.':'Prüfe den erkannten Text vor der Suche.','Il testo riconosciuto comparirà qui; puoi correggere marca o modello.':'Der erkannte Text erscheint hier; du kannst Marke oder Modell korrigieren.','Cerca marca e modello':'Marke und Modell suchen','Lettura delle barre con recupero automatico delle cifre tramite OCR.':'Barcode-Lesung mit automatischer Ziffernerkennung per OCR.','Annulla analisi':'Analyse abbrechen','Il codice identifica la confezione; la scheda riporta soltanto i dati presenti nei cataloghi collegati. I dati mancanti restano esplicitamente tali.':'Der Code identifiziert die Verpackung; das Blatt zeigt nur Daten aus verbundenen Katalogen. Fehlende Daten bleiben ausdrücklich als fehlend gekennzeichnet.','Codice acquisito':'Code erfasst','Scheda prodotto':'Produktblatt','Cerco il prodotto…':'Produkt wird gesucht…','Caratteristiche principali':'Hauptmerkmale','Informazioni aggiuntive':'Zusätzliche Informationen','Leggi opinioni del prodotto':'Produktbewertungen lesen','Il prodotto fisico resta al centro. ScanDixit aggiunge le informazioni che aiutano a scegliere.':'Das physische Produkt bleibt im Mittelpunkt. ScanDixit ergänzt Informationen, die bei der Auswahl helfen.','Torna a FiCard':'Zurück zu Fi-Card'}
};
function lang(){
 try{return root.FiCardI18n?.language?.()||root.localStorage.getItem(STORE)||'it'}catch{return 'it'}
}
function tr(s){const l=lang().split('-')[0];return maps[l]?.[s]||s}
function skip(n){return n?.parentElement?.closest('script,style,svg,canvas')}
function textNode(n){
 if(!n||n.nodeType!==3||skip(n))return;
 const raw=n.nodeValue||'',lead=raw.match(/^\s*/)?.[0]||'',trail=raw.match(/\s*$/)?.[0]||'';
 const core=raw.slice(lead.length,raw.length-trail.length); if(!core)return;
 const next=tr(core);if(next!==core)n.nodeValue=lead+next+trail
}
function element(el){
 if(!el||el.nodeType!==1)return;
 for(const a of ['placeholder','aria-label','title'])if(el.hasAttribute(a)){const v=el.getAttribute(a),n=tr(v);if(n!==v)el.setAttribute(a,n)}
 for(const n of el.childNodes)if(n.nodeType===3)textNode(n);
 for(const ch of el.children)element(ch)
}
function run(){
 const l=lang().split('-')[0];document.documentElement.lang=l;
 if(l==='it'||!maps[l])return;
 element(document.body);
 new MutationObserver(ms=>{for(const m of ms)for(const n of m.addedNodes){if(n.nodeType===3)textNode(n);else if(n.nodeType===1)element(n)}}).observe(document.body,{subtree:true,childList:true,characterData:false})
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run,{once:true});else run();
})(window);
