const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
const root=path.join(__dirname,'..'),window={};vm.runInNewContext(fs.readFileSync(path.join(root,'ficard-stores.js'),'utf8'),{window});const S=window.FiCardStores;
const center={lat:41.9,lng:12.4},area=S.boundsFor(center),node=(id,name='Conad',lat=41.9)=>({type:'node',id,lat,lon:12.4,tags:{name,shop:'supermarket',unneeded:'discard'}});
function storage(){const data=new Map();return {getItem:k=>data.get(k)||null,setItem:(k,v)=>data.set(k,v),removeItem:k=>data.delete(k)}}
test('cache accumulates visited areas, updates OSM IDs without duplicates, survives reload',()=>{const st=storage();let c=S.mergeCache(null,{elements:[node(1)]},area);c=S.mergeCache(c,{elements:[node(1,'Conad City'),node(2)]},S.boundsFor({lat:42,lng:12.5}));assert.equal(c.elements.length,2);assert.equal(c.elements.find(e=>e.id===1).tags.name,'Conad City');assert.equal(c.elements[0].tags.unneeded,undefined);assert.equal(S.writeCache(st,c),true);assert.equal(S.readCache(st).elements.length,2);assert.equal(S.cacheCovers(S.readCache(st),S.boundsFor(center,1000)),true)});
test('small GPS movements and new cards reuse coverage; expired and unvisited areas refresh',()=>{const now=Date.now(),c=S.mergeCache(null,{elements:[node(1)]},area,now);assert.equal(S.cacheCovers(c,S.boundsFor({lat:41.905,lng:12.405},1000),now),true);assert.equal(S.cacheCovers(c,S.boundsFor({lat:42.1,lng:12.4},1000),now),false);assert.equal(S.cacheCovers(c,area,now+S.CACHE_AGE),false);assert.equal(S.parse(c,[{id:'new-card',names:['Conad']}])[0].cardId,'new-card')});
test('old six-query cache imports all areas and failed storage preserves the old copy',()=>{const st=storage();st.setItem('ficard.nearby-shops.v3',JSON.stringify([{key:'41.9,12.4/Conad',at:Date.now(),data:{elements:[node(1)]}},{key:'42,12.5/Lidl',at:Date.now(),data:{elements:[node(2,'Lidl',42)]}}]));const c=S.readCache(st);assert.equal(c.elements.length,2);assert.equal(c.zones.length,2);const fail={...st,setItem:()=>{throw Error('quota')}};assert.equal(S.writeCache(fail,c),false);assert.ok(st.getItem('ficard.nearby-shops.v3'));assert.equal(S.writeCache(st,c),true);assert.equal(st.getItem('ficard.nearby-shops.v3'),null);assert.equal(S.readCache(st).elements.length,2)});
test('corrupt cache is harmless and bounded eviction invalidates coverage',()=>{const st=storage();st.setItem('ficard.nearby-shops.v4','broken');assert.equal(S.readCache(st).elements.length,0);const c=S.mergeCache(null,{elements:Array.from({length:8001},(_,i)=>node(i))},area);assert.equal(c.elements.length,8000);assert.equal(S.cacheCovers(c,area),false)});
const ui=fs.readFileSync(path.join(root,'ficard-stores-ui.js'),'utf8');
function searchFixture(){const st=storage(),ctx={S:{...S},localStorage:st,AbortController,cards:[{id:'c',name:'Conad'}],results:[],searchCenter:null,controller:null,requestId:0,busy:false,status:'',lastKey:'',matchedCards:'',shopCache:S.mergeCache(null,{elements:[node(1)]},area),descriptors:()=>ctx.cards.map(c=>({id:c.id,names:[c.name]})),renderLocations(){},renderShopUpdates(){},console};vm.createContext(ctx);vm.runInContext(ui.slice(ui.indexOf('function matchCachedShops('),ui.indexOf('const baseSmartCarousel='))+ui.slice(ui.indexOf('async function search('),ui.indexOf('function renderDetail()')),ctx);return ctx}
test('search skips network inside cache and refresh merges only new shops without clearing old ones',async()=>{const c=searchFixture();let calls=0;c.S.request=async()=>{calls++;return {elements:[node(2,'Conad',41.901)]}};await c.search(center);assert.equal(calls,0);assert.equal(c.results.length,1);c.cards.push({id:'new',name:'Conad'});await c.search({lat:41.901,lng:12.401});assert.equal(calls,0);assert.equal(c.results.length,2);await c.search(center,true);assert.equal(calls,1);assert.equal(c.shopCache.elements.length,2);assert.equal(c.results.length,4);assert.equal(c.busy,false)});
test('outage and simultaneous identical queries retain cached shops and send one request',async()=>{const c=searchFixture();let calls=0,reject;c.S.request=()=>{calls++;return new Promise((_,r)=>reject=r)};c.console={warn(){}};const first=c.search(center,true);await c.search(center,true);assert.equal(calls,1);assert.equal(c.results.length,1);reject(Error('offline'));await first;assert.equal(c.results.length,1);assert.equal(c.shopCache.elements.length,1);assert.equal(c.busy,false)});
test('map batches markers, creates popups on demand, and reuses the layer on status changes',()=>{let markers=0,popups=0,layers=0,callbacks=[];const map={invalidateSize(){},fitBounds(){}};const c={document:{getElementById:()=>({classList:{contains:()=>true}}),createElement:()=>({append(){}})},window:{L:{}},L:{markerClusterGroup:()=>{layers++;return {addTo(){return this},addLayers(items){assert.equal(items.length,2)},remove(){}}},divIcon:x=>x,marker:()=>{markers++;return {bindPopup(fn){callbacks.push(fn);return this}}}},overviewMap:map,overviewLayer:null,currentPosLayer:null,currentPos:null,searchCenter:null,mapFramed:true,mapSignature:'',filtered:()=>[{c:{id:'a',name:'Conad'},l:{lat:41.9,lng:12.4},d:0},{c:{id:'b',name:'Lidl'},l:{lat:41.901,lng:12.4},d:10}],mapBrandVisual:()=>({color:'#fff'}),mapBrandInnerHtml:()=>'',mapCardPinIcon:()=>({}),esc:x=>x,row:()=>{popups++;return {}},setTimeout(){}};vm.createContext(c);vm.runInContext(ui.slice(ui.indexOf('function shopSignature('),ui.indexOf('const savedFavorite='))+ui.slice(ui.indexOf('renderOverviewMap=function(){'),ui.indexOf('function renderShopUpdates()')),c);c.renderOverviewMap();assert.equal(markers,2);assert.equal(layers,1);assert.equal(popups,0);c.renderOverviewMap();assert.equal(markers,2);assert.equal(layers,1);callbacks[0]();assert.equal(popups,1)});
