const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
const root={};vm.runInNewContext(fs.readFileSync(require('node:path').join(__dirname,'../ficard-stores.js'),'utf8'),{window:root,AbortController,setTimeout,clearTimeout,URLSearchParams,fetch});const S=root.FiCardStores;
function service(fetcher){const window={};vm.runInNewContext(fs.readFileSync(require('node:path').join(__dirname,'../ficard-stores.js'),'utf8'),{window,fetch:fetcher,AbortController,setTimeout,clearTimeout,URLSearchParams});return window.FiCardStores}
test('shop service falls back on outages and rejects incomplete results',async()=>{const urls=[];const s=service(async url=>{urls.push(url);return urls.length===1?{ok:false}:{ok:true,json:async()=>({elements:[]})}});assert.equal((await s.request('query')).elements.length,0);assert.equal(urls.length,2);const incomplete=service(async()=>({ok:true,json:async()=>({remark:'timed out',elements:[]})}));await assert.rejects(incomplete.request('query'),/incompleta/)});
test('cancelled shop request never uses a fallback provider',async()=>{const controller=new AbortController();let count=0;const s=service(async()=>{count++;controller.abort();throw Error('cancelled')});await assert.rejects(s.request('query',controller.signal));assert.equal(count,1)});
test('shop matching uses whole brand names, accents and aliases',()=>{assert.equal(S.matches({name:'Conad City Roma'},['Conad']),true);assert.equal(S.matches({brand:'Tigota'},['Tigotà']),true);assert.equal(S.matches({name:'Comodo market'},['MD']),false);assert.equal(S.matches({name:'Cooperativa locale'},['Coop']),false);assert.ok(S.names({}, {},'coop').includes('Ipercoop'))});
test('shop query uses bounded indexed categories and retains node coordinates',()=>{const q=S.query({lat:41.9,lng:12.4},['Conad','A";out;'],3000,[41.87,12.4,41.9,12.44]);assert.ok(q.includes('(41.87000,12.40000,41.90000,12.44000)'));assert.ok(q.includes('[timeout:25]'));assert.ok(q.includes('out body center;'));assert.ok(!q.includes('A";out;'));assert.equal((q.match(/nwr/g)||[]).length,2);assert.throws(()=>S.query({lat:NaN,lng:0},['Conad']));assert.throws(()=>S.query({lat:91,lng:0},['Conad']));assert.throws(()=>S.query({lat:41.9,lng:12.4},['Conad'],3000,[40,12,43,13]),/Avvicina/)});
test('point shops are retained even when no area shop exists',()=>{const shops=S.parse({elements:[{type:'node',id:11,lat:41.88,lon:12.42,tags:{shop:'supermarket',name:'Conad City'}}]},[{id:'c',names:['Conad']}]);assert.equal(shops.length,1);assert.equal(shops[0].point.lat,41.88);assert.equal(shops[0].point.osmId,'node/11')});
test('shop parser supports areas, filters unrelated brands and deduplicates nearby nodes',()=>{const ds=[{id:'c',names:['Conad']}];const data={elements:[{type:'way',id:1,center:{lat:41.9,lon:12.4},tags:{brand:'Conad','addr:street':'Via Roma'}},{type:'node',id:2,lat:41.90001,lon:12.4,tags:{name:'Conad'}},{type:'node',id:3,lat:41.8,lon:12.4,tags:{name:'Lidl'}},{type:'node',id:4,lat:Infinity,lon:0,tags:{name:'Conad'}}]};const shops=S.parse(data,ds);assert.equal(shops.length,1);assert.equal(shops[0].cardId,'c');assert.equal(shops[0].point.osmId,'way/1');assert.equal(shops[0].point.address,'Via Roma')});
